name: newproject
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  google_ml_kit: ^0.20.0
  file_picker: ^10.1.8
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  badges: ^3.1.2
  lucide_icons: ^0.257.0
  vector_math: ^2.1.4
  speech_to_text: ^7.0.0
  mime: ^2.0.0
  permission_handler: ^12.0.0+1
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  webview_flutter: ^4.12.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  camera: ^0.10.5+9
  cached_network: ^2.1.0
  cached_network_image: ^3.4.1
  model_viewer_plus: ^1.9.3
  fluttertoast: ^8.2.12
  image: ^4.5.4
  carousel_slider: ^5.0.0
  emailjs: ^4.0.0
  razorpay_flutter: ^1.4.0
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  provider: ^6.1.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fashion_classifier.tflite
    - assets/model_config.json