// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUYZn-3QazaIAKZyYfu1D-tSIhu6TFYus',
    appId: '1:475033418027:web:b03464e8214a422d3bed6e',
    messagingSenderId: '475033418027',
    projectId: 'newproject-75535',
    authDomain: 'newproject-75535.firebaseapp.com',
    storageBucket: 'newproject-75535.firebasestorage.app',
    measurementId: 'G-EZQD153WC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-I6ZwFASWIV0ST1-QNi8QYOrCmE5sCeM',
    appId: '1:475033418027:android:b6e30cea86a53d993bed6e',
    messagingSenderId: '475033418027',
    projectId: 'newproject-75535',
    storageBucket: 'newproject-75535.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUYZn-3QazaIAKZyYfu1D-tSIhu6TFYus',
    appId: '1:475033418027:web:ce81a34f3cd107343bed6e',
    messagingSenderId: '475033418027',
    projectId: 'newproject-75535',
    authDomain: 'newproject-75535.firebaseapp.com',
    storageBucket: 'newproject-75535.firebasestorage.app',
    measurementId: 'G-9259NR7NJF',
  );
}
